settings:
  title: 'OnXbox Status'
  url: 'https://status.onxbox.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: onxboxwww
    name: www.onxbox.co
    description: 'OnXbox Main Website'
    url: 'https://www.onxbox.co/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: onxboxcommunity
    name: forums.onxbox.co
    description: 'OnXbox Community Forums'
    url: 'https://forums.onxbox.co/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: onxboxmail # unique identifier
    name: mail.onxbox.net
    description: 'The frontend to our free email experience.' # default=empty
    url: 'https://mail.onxbox.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  
  - id: onxboxcdn1
    name: userimg.gs.onxbox.net
    description: 'OnXbox CDN'
    url: 'https://userimg.gs.onxbox.net/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true 
     
  - id: onxboxmailcdn
    name: mailimg.onxboxusercontent.com
    description: 'This Server is the mail content (images, css, scripts, etc) proxy handler.'
    url: 'https://mailimg.onxboxusercontent.com/'
    method: GET
    expectStatus: 403
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: onxboxaccounts
    name: account.onxbox.co
    description: 'OnXbox Accounts Server'
    url: 'https://account.onxbox.co/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true  

    - id: onxboxprofile
    name: profile.onxbox.co
    description: 'OnXbox Profiles Server'
    url: 'https://profile.onxbox.co/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: onxboxgraph
    name: graph.onxbox.co
    description: 'OnXbox Graph API'
    url: 'https://graph.onxbox.co/me'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: postmaster # unique identifier
    name: postmaster.onxbox.net
    description: 'Postmaster handles our emails.' # default=empty
    url: 'https://postmaster.onxbox.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
